name: Mayhem

on:
  push:
    branches: [ main ]
  #workflow_dispatch:

permissions: write-all

jobs:
  test-mayhem:
    name: test for mayhem
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Start mayhem test
      #   id: run-mayhem
        uses: actions/checkout@v3
      #      mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
      #      owner: keito
      #     fail-on-defects: true
      #     sarif-output: sarif
      #     junit-output: junit
      #     coverage-output: coverage
      - name: set env
        run: |
              DATETIME=`date "+%Y%m%d"_"%H%M%S"`
              echo ${DATETIME}
      - name: run test 
        run: |
              mayhem run --all -b ${DATETIME} ./test-pkg
              mayhem wait --sarif sarif --verbose calc-a/calc-a/${DATETIME}
              mayhem sync ./test-pkg

      - name: Upload SARIF file(s)
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif

      # - name: Upload JUNIT file(s)
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: junit
      #     path: junit

      # - name: Upload coverage to Codecov
      #   if: always()
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: coverage/*.lcov
      #     flags: vulnerability-tests
      #     name: mayhem
